on:
  push:
    branches:
      - main
name: ðŸš€ Build and Deploy snAcks!
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2

    - name: Set up Node.JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: ðŸ”¨ Build snAcks
      run: |
        npm install
        npm run build
        npm run build-capacitor-android
        npx cap sync
    
    - name: ðŸ“‚ Upload files to ats.agnelli.it/snacks
      run: |
        sshpass -p ${{ secrets.SCP_PASSWD }}  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_CONNSTRING }} -p22 "cd snacks && rm -rf *"
        sshpass -p ${{ secrets.SCP_PASSWD }}  scp -o StrictHostKeyChecking=no -r www/*  ${{ secrets.SCP_CONNSTRING }}:snacks/
    
    - name: ðŸ”¨ Install Java JRE and JDK
      run: |
        sudo apt-get install default-jre openjdk-17-jdk-headless
        
    - name: ðŸ”¨ Build snAcks for Android
      run: |
        cd android
        node update_gradle.js
        ./gradlew :app:bundleRelease
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore ./sasy.jks app/build/outputs/bundle/release/app-release.aab upload -storepass ${{ secrets.KEYSTORE_PASS }}
        
    - name: ðŸ”¨ Upload snAcks on Google Play Store
      run: |
        echo -e ${{ secrets.PRIVATE_KEY}} >> key.txt
        node upload.js -c ${{ secrets.CLIENT_EMAIL }}


        
        
